---
title: "ChromeAnalyzR"
author: "Toby C"
date: "November 29, 2016"
output:
  html_document:
    keep_md: yes
    theme: 'yeti'
    highlight: 'tango'
    css: 'table.css'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message=F, warning=F)

library("dplyr")
library("urltools")
library("magrittr")
library("RSQLite")
library("highcharter")


#Function that extracts domain from the url hence the urltools !
extract.domain <- function(url){
  df <- suffix_extract(domain(url))
  if (!(is.na(df$domain) && is.na(df$suffix))){
    paste(df$domain, df$suffix, sep='.')
  } else {
    return(url)
  }
}
```


```{r }

# create a connection object. 
con <- dbConnect(RSQLite::SQLite(), dbname="/path/to/chrome/history")

# get a list of all tables
# alltables = dbListTables(con)

#query <- 'SELECT urls.url, urls.visit_count FROM urls, visits WHERE urls.id = visits.url;'
query <- 'SELECT datetime(((visits.visit_time/1000000)-11644473600),"unixepoch") as datetime, urls.url, urls.visit_count,
urls.title FROM urls, visits WHERE urls.id = visits.url;'
# get the url table as a data.frame object.
History.data <- dbGetQuery(con, query)
# storing the date values as a date object
# it's a good idea to store date and time values as date object, not as strings or numbers. 
# manipulating date as strings can be difficult. 
# also date and time objects includes functions for extracting character representation of date object.

History.data$datetime = as.POSIXct(History.data$datetime)

#add a new column by applying (lapplying actually) extract.domain function to url column to extract the domain names 
History.data$domain <- 
  lapply(History.data$url, extract.domain) %>% 
  unlist() %>%
  factor()



```


## Stats {.tabset .tabset-fade .tabset-pills}

### Top Domains
```{r topdomain}
group_by(History.data, domain) %>%
  summarise(visitcount = n()) %>% 
  arrange(desc(visitcount)) %>%
  head(., 10) %>%
  knitr::kable(., format='markdown')
```

### Top Urls 
```{r}
#Top ten urls
group_by(History.data, url) %>%
  summarise(visitcount = n()) %>% 
  arrange(desc(visitcount)) %>%
  head(., 10) %>%
  knitr::kable(., format='markdown')
```

### Bussiest Days
```{r}
# Date stats
Date.stats <- 
  mutate(History.data, date = strftime(datetime, '%b %d')) %>%
  group_by(date) %>%
  summarise(visitcount = n())

# Top ten busiest dates

mutate(History.data, date = strftime(datetime, '%a, %B %d, %Y')) %>%
  group_by(date) %>%
  summarise(visitcount = n()) %>%
  arrange(desc(visitcount)) %>%
  head(., 10) %>%
  knitr::kable(., format='markdown')

#---------------------------

```



```{r}


#Day of week stats
Weekday.stats <-
  mutate(History.data, weekday = strftime(datetime, '%a')) %>%
  count(., weekday)

# Hour 
Hr.stats <-
  mutate(History.data, hr = strftime(datetime, '%I %p')) %>%
  count(., hr)

#Day of the month stats (day as a number)
Day.stats <- 
  mutate(History.data, day = as.integer(format.Date(datetime, '%d'))) %>%
  count(., day)

#Months stats
Month.stats <-
  mutate(History.data, month = strftime(datetime, '%b')) %>%
  count(., month)
```

```{r include=F}
visits.today <- filter(History.data, as.Date(datetime) == Sys.Date()) %>% nrow()
avg.visits.per.day <- mean(Date.stats$visitcount) %>%
  round()
med.visits.per.day <- median(Date.stats$visitcount)

```

## Daily stats

Daily stats             | 
----------------        | -------------
Average visits per day: | `r avg.visits.per.day`
Median Visits Per Day:  | `r med.visits.per.day`
Today:                  | `r visits.today`

## Let us C!

```{r}
highchart(width=800, height=300) %>%
  hc_xAxis(categories = Date.stats$date) %>%
  hc_add_series(data=Date.stats$visitcount, type='area', name='Date') %>% 
  hc_colors(colors = '#278DBC') %>%
  hc_title(text='Visits per Day', align ='left')
```

```{r chart01, results='asis', comment=NA}
plot <- function(data, x, y, title){
  highchart(width=800, height=300) %>%
  hc_chart(type='column') %>%
  hc_xAxis(categories = x) %>%
  hc_add_series(data = y, name='Visit Count')%>%
  hc_colors(colors = '#278DBC') %>%
  hc_tooltip(borderWidth=4) %>% 
  hc_title(text=title, align ='left')
}

plot(Hr.stats, Hr.stats$hr, Hr.stats$n, title= 'Time of Day')
plot(Weekday.stats, Weekday.stats$weekday, Weekday.stats$n, 'Day of week')
plot(Day.stats, Day.stats$day, Day.stats$n, 'Day of Month')
plot(Month.stats, Month.stats$month, Month.stats$n, 'Month' )

```



